node('win_slave1') {
    stage 'build'
    cleanWs()
    git( url: 'https://github.com/izealinc/petclinic.git',
         branch: '${BRANCH_NAME}'
       )
    bat 'mvn versions:set -DnewVersion=1.5.1-SNAPSHOT'
    bat 'mvn package'
    echo 'Completed build'
    stage 'unit test'
    junit '**/target/surefire-reports/*.xml'
    stage 'archive'
    archiveArtifacts '**/target/*.jar'
    echo 'Completed archiving'
}
