node ('ubuntu_slave5'){
   stage 'build'
   cleanWs()
    if (isUnix()) {
        //sh 'git clone -b ${BRANCH_NAME} https://github.com/sasi9k/petclinic-infra.git'
        //dir('petclinic-infra') {
            sh 'ansible-playbook pipelines/karthik/ansible/files.yml -i 192.168.1.221, -u desktop6izealinc'
        //}
    } 
}
