node('win_slave1') {
   stage 'build'
   cleanWs()
   sleep 3
   git( url: 'https://github.com/sasi9k/petclinic.git',
         branch: '${BRANCH_NAME}'
       )
//   git 'https://github.com/izealinc/petclinic.git'
//   git 'https://github.com/spring-projects/spring-petclinic.git'
//   bat 'git clone https://github.com/spring-projects/spring-petclinic.git'
//   dir('spring-petclinic') {
       bat 'mvn versions:set -DnewVersion=1.5.1-SNAPSHOT'
       bat 'mvn package'
//   }
   echo 'Build Completed'
   stage 'test report'
   junit '**/target/surefire-reports/*.xml'
   stage 'Archive'
   archiveArtifacts '**/target/*.jar'
   echo 'Completed Archiving'
   stage 'Deploy'
   build job: 'kalyan/deploy', propagate: true, wait: true
   echo 'Completed Deploy'
}
